services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: sb-concepts-lab-jenkins
    user: root
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins-home:
