spring:
  config:
    activate:
      on-profile: localstack

server:
  port: 8090

logging:
  structured:
    format:
      console: logstash
  level:
    root: INFO
    sb.concepts.lab: DEBUG
    software.amazon.awssdk: WARN

app:
  profile-name: localstack
  description: Local AWS-compatible profile backed by Docker LocalStack.
  aws:
    region: us-east-1
    account-id: "000000000000"
    access-key: test
    secret-key: test
    s3:
      endpoint: http://localhost:4566
      bucket-prefix: sb-concepts-lab
