spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8083

logging:
  structured:
    format:
      console: logstash
  level:
    root: INFO
    sb.concepts.lab: INFO
    org.springframework: WARN

app:
  profile-name: prod
  description: Production profile that simulates an AWS cloud runtime without calling AWS.
  aws:
    region: us-east-1
    account-id: "123456789012"
    access-key: use-iam-role-in-real-prod
    secret-key: use-secrets-manager-in-real-prod
    s3:
      endpoint: aws-managed
      bucket-prefix: sb-concepts-lab-prod
